[workspace]
members = ["crates/elm-magic-macros", "crates/elm-magic-egui"]

[package]
name = "elm-magic"
version = "0.1.0"
edition = "2021"
description = "State is a variable, events are assignment, the screen is the function body. A lightweight pure-functional UI library disguised as JS/JSX via macros."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jaywoo0830a/elm"
keywords = ["ui", "gui", "jsx", "elm", "macros"]
categories = ["gui", "rust-patterns"]

[dependencies]
elm-magic-macros = { path = "crates/elm-magic-macros", version = "0.1.0" }

